use crate::{ScheduleID, World};

/// A type-erased system taking no input and producing no output, as stored in a `Schedule`.
pub type BoxedSystem = Box<dyn System<(), ()>>;

/// A unit of logic that can be run against a `World` by the scheduler.  Implementors
/// are generated by the `#[system]` attribute macro, which builds this trait around a
/// plain function and extracts its arguments from the `World` via `SystemExtractor`.
pub trait System<I, O>: Send + Sync {
    /// Returns this system's name, used for logging and diagnostics.
    fn name(&self) -> &str;

    /// Returns this system's scheduling priority.  Systems with a higher priority are
    /// run before those with a lower priority within the same schedule tile.
    fn priority(&self) -> i32;

    /// Runs this system once against the given `World`.
    fn execute<'a>(
        &self,
        schedule_id: ScheduleID,
        world: &'a World,
        inputs: &'a I
    ) -> O;
}
